# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 139.196.159.52
    # 端口，默认为6379
    port: 16379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

alipay:
  appId: 9021000141662885
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCAgNpVn+dQ8h11EPEJHzC+jO9vWxQdfgLP/yr3scbTVCB7gICBcz3lZF+qAvph92MieJbFjvEbcjakWeD1or50XKlbNJpl5C7wIDKf/4VXqxbOTmeTwvmrbakqdBjciVXEZkABzfWbVk3iF2ntwVj+kUZZyAAt9T2Z9MOeSf9IcdtLQZV/lMSLorJ/rPzOKYuB5ekFLLsllv62xL37uoxiB10YJ8mzWNDJMMK1OCyyz1B5iHT6W9UjNvg1rhI8Im/bkc5sSgbEb4cnXkOlrFDzI60Gu3GPTq9TqbHDHe9rBmlLNAJ7S1tv6z85/fG2E3TXSqAMFG6nyr/sqQDyrJCZAgMBAAECggEAFvDqCadGcJkI0UF5Bpve4+XdSRAFg05fyipPzXCbglbeha3nQzUDs9Q7j+qAMMUtmZXVtOdT/AZj4ut40eGABt4UDghSGCaoio30+8NuVrxgkexFaYfBcu1c6gtX9Oc/vJRUkP3n/xdlSBvN+XgvHyNoX9bo0Uua98VOtw+W16PbMOv52RbDHY/x3dUFNC8gJCjMk1lHy9FOKYFq51ZSiQNofo+n/1vRRyU4FZdyvEnlmeMr7/Jfx4PqkaNLPsOoMFgxnpN64D/2Ht+ixZ411Xn0uS2rsfiWpdOVqNO/GmZd8QoLL+IB/bQuzkkm7yAkQQlY+ocxh4DDL7C0qq18kQKBgQC4w86C3e/3HoRVfOmxwE2qTIrweynENpnGgRmhkxD/QIOIRbc+jV7QEUUrZd5fVcAfrFFj7VLhr/Za4c7yWnRvH5DOcg9FBTLopFV+2Tgsv2d3Vmbz66bHRpVEdrjysXLnBzV6ECdCl1YVcDK7+ICCgq1QdeOFkDQWicJuK5pX/wKBgQCyDBAGh7ldkRxGepqd6Re8ukec0EApJZQQJp+5Z9kI0CpDlLvX7Rd7y9INOi5MAz+i2MBCm3gb7mbQ1/zzM1x0sz5PNhHwqhUB9iyHazIpjDlRMH8YNbkMDps4mf7DhsgaCmfQ7nwD2OKbxks6HErXssCgG+uBO5jg3W7WGFTXZwKBgA/6v02KLErPFNrf5sY8v3rPC+UogcA6iKomWDUlJv8scTPD88kxKNYN6FGMieLs46TZnmBqEhT6xu+tP9yt/gvuSvPP4YoynOiJ7er+lmEoXKZxjo3h/5aUgCxfqDc1KZ7ZfMKFyx9zPzqzbW/cWiDvdFXVHExc4GRinbIxizO5AoGBAIXwJxoSffKSWBf44VmLYOz7oSWpT6rkdwbTV3KtWYqUtkaSm+CqnfDl+kUzEGLkSrnhnng85lT0uem/oaz+ZT3xHR2Pil1mRVltbEAO9vRkZTXbarC2sVcNod0pk4pZWSylyUVWMnrebFJNEIhNgkvTT67icf6M68u1KEzsjt5fAoGAbQDhbfmjgOVUUPDm3noaEtouljfZYOJRm1qDO/nUbYVyTuz5y6mHDBevxMc0z+TyXlSsfvsZUegWH8IySElD1H+3eEzSRkxVrMM07CzqHqnYfJ1RonLmiTOfy7GvPDr/QWPT7A0/eBUudCYHcr/j21JyMjr4dEAr+Z8ZkD1ubt8=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApOp0AOSMksvV0rGgGSUiPcWZVdakHu7gbLz0jxg7WQ+paZT/8QY12y0STs1iA0A2jU1gMfmN8Ts3hdGEtuX8sx0KOQTT9T7ZgzJ6It8BTpxroWkqK9LdjyLPE545+0EYeSVt/k7X6lVVM4ZReZX/3+g4h1TwQCX8MazsNayyezaQ4fn/kJw8VKLovIGWDKPEtQ1VoaRnro5iXC+VSdFn8es+1JuE8+p8xvWlapBeesEBZTwNOxVe2NB7H9sUnXjnAD1si5q2yUrlfVi6FOjnYdEtDlI+fLV8H0l53fAit/jrs+WgKCHP+wi+GHRaVY2aesVopGJPa6givGlkluXUuwIDAQAB
#  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDECiC3gx2bvcvy0IZntm1DNPCeGzN2V9f7hCXyhA7FPj0kQSHbu/vywh9vB5QEOiGHCJO7X/qtG9MyGMqZdl+3mnq0GunUEOUW0KUNQyvKRlc05yT/mzrKucb8Jx0u+H/0eh7BFP1lg6iQ3/xCywG0mwHAoPdYvQ3y/VY3TBwpiZmIV2wxqEwEM2KZGRDFsJ568/s6WFIe/6E8VJDLHpCfV/C9CsBnZP5V+mKFYOo/QtmtpohuF8fgGqNM7WTfDDm14ba7flZoRAZeiYdrSdS0woFHZ6f87Ms4SrDj4PkqnWXyjMsYuiHWxpGR/FVYPZLHZuSRrZhdUZCDjdUNvnPPAgMBAAECggEBAILHXtwNlAr5qrzpb0Bw6qMTBhHzg3lHUMZxef83KcNbqd4ttTCpT4K7Dc07+Pp47TTv+93cQZaKIXIiJ8YIugH6BDFyYtseCjYWKoWWcfgWxMZ+DKiYHbhwBtbgIQ/cpz+o2CtmnUTDeAht5BOK6jBZ1+lxeJCyTkPzzThGheMOxHKIMUlTKCErGo92kVahj21blyM/iJoy/3Rhnp/7lMKKNE45BQEx+XU8LmuBNMN96Y6zwWAnoUzhWc32cPKIB1y9vVv4ydpdo6oPO1iT0HiqcpxETQ+efoQlQsQ8EYgjwWJtFn1njLRuhHZPWf2rTzcfzGWzXqUVifO2OBP2o4ECgYEA86ECB+qXrTGC6kNqZbdgcR32aa8kNG59rERoF7ZUGRTW+MeuIeSsARLFN/h38vMz+jcLTvnm6sBLhfbedCwfeu1D1flgYA0WrU44nCT+I1Ud6PcEyBUB7o4kWydX9D1yKzt3aceDgn0P1+br4vSeirurgj2eAYjmCgkxDNQQ4ncCgYEAzf5+c34se9o2U7wfXnutCFD7GzlIMHauftUo1jJiEl62DJEt2bU51yLyQJGYuK/FuHZjSvNRgVTSBs71yqgBKG9Nk2jYFaESGLPUeI5Mk6YIHktJYkugZELiawqhWBiP1yLtItw1rFmB7Wbub8iJvGEWMXA3GYVG2joXkm+mN2kCgYEAroDfEYiJB/b0zJNpPF4y6BMMEvruNdgGkEOXQ5THfAefSybLpV9DjKlDNin00MI+srSGlxUMv4zpC5WeFRwdmFEmS7eJvoLhgVUL21vr5Kbs+5cjh6T0c0jA5cGykDEK+8hmahAMNIUbugufXjrU7I4r9OfpqzPBgeK/jW7AgVUCgYEAuaxqzi8saXaHAXLP05omnRhhPmijaQuQvUHlTSycuXIlJa62ZUW0nPYi5ZBW2CGXVm1fkm8/SBPsO7bQVZqZcJjik7wtCVHlvd5Z5VBeNbeyGZxCyRbhu32OGG28gGujO4d/t6xFtNP5CMN+p8NaYzIfjvBWueonswwpsxRv/gECgYAg6s4QwCfqXsLNCgFNkJ3zCbqzxK2P/9Rs6+icaJG5ISK3l1Xn+cg6rnnzrcIXbFnn07nJ2WTeMU4me99lx4ab3QUtHqDhJFtWVlFmp+zLjYJVhKcwpIl7AeBzlZn+AFeJ10apVz92klgh3xAl0go5zWkBy6knD7Uy64EFnxWUPQ==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApOp0AOSMksvV0rGgGSUiPcWZVdakHu7gbLz0jxg7WQ+paZT/8QY12y0STs1iA0A2jU1gMfmN8Ts3hdGEtuX8sx0KOQTT9T7ZgzJ6It8BTpxroWkqK9LdjyLPE545+0EYeSVt/k7X6lVVM4ZReZX/3+g4h1TwQCX8MazsNayyezaQ4fn/kJw8VKLovIGWDKPEtQ1VoaRnro5iXC+VSdFn8es+1JuE8+p8xvWlapBeesEBZTwNOxVe2NB7H9sUnXjnAD1si5q2yUrlfVi6FOjnYdEtDlI+fLV8H0l53fAit/jrs+WgKCHP+wi+GHRaVY2aesVopGJPa6givGlkluXUuwIDAQAB
  notifyUrl:  http://64te6c.natappfree.cc/alipay/notify

alipaymp:
  appId: 9021000141662885
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCAgNpVn+dQ8h11EPEJHzC+jO9vWxQdfgLP/yr3scbTVCB7gICBcz3lZF+qAvph92MieJbFjvEbcjakWeD1or50XKlbNJpl5C7wIDKf/4VXqxbOTmeTwvmrbakqdBjciVXEZkABzfWbVk3iF2ntwVj+kUZZyAAt9T2Z9MOeSf9IcdtLQZV/lMSLorJ/rPzOKYuB5ekFLLsllv62xL37uoxiB10YJ8mzWNDJMMK1OCyyz1B5iHT6W9UjNvg1rhI8Im/bkc5sSgbEb4cnXkOlrFDzI60Gu3GPTq9TqbHDHe9rBmlLNAJ7S1tv6z85/fG2E3TXSqAMFG6nyr/sqQDyrJCZAgMBAAECggEAFvDqCadGcJkI0UF5Bpve4+XdSRAFg05fyipPzXCbglbeha3nQzUDs9Q7j+qAMMUtmZXVtOdT/AZj4ut40eGABt4UDghSGCaoio30+8NuVrxgkexFaYfBcu1c6gtX9Oc/vJRUkP3n/xdlSBvN+XgvHyNoX9bo0Uua98VOtw+W16PbMOv52RbDHY/x3dUFNC8gJCjMk1lHy9FOKYFq51ZSiQNofo+n/1vRRyU4FZdyvEnlmeMr7/Jfx4PqkaNLPsOoMFgxnpN64D/2Ht+ixZ411Xn0uS2rsfiWpdOVqNO/GmZd8QoLL+IB/bQuzkkm7yAkQQlY+ocxh4DDL7C0qq18kQKBgQC4w86C3e/3HoRVfOmxwE2qTIrweynENpnGgRmhkxD/QIOIRbc+jV7QEUUrZd5fVcAfrFFj7VLhr/Za4c7yWnRvH5DOcg9FBTLopFV+2Tgsv2d3Vmbz66bHRpVEdrjysXLnBzV6ECdCl1YVcDK7+ICCgq1QdeOFkDQWicJuK5pX/wKBgQCyDBAGh7ldkRxGepqd6Re8ukec0EApJZQQJp+5Z9kI0CpDlLvX7Rd7y9INOi5MAz+i2MBCm3gb7mbQ1/zzM1x0sz5PNhHwqhUB9iyHazIpjDlRMH8YNbkMDps4mf7DhsgaCmfQ7nwD2OKbxks6HErXssCgG+uBO5jg3W7WGFTXZwKBgA/6v02KLErPFNrf5sY8v3rPC+UogcA6iKomWDUlJv8scTPD88kxKNYN6FGMieLs46TZnmBqEhT6xu+tP9yt/gvuSvPP4YoynOiJ7er+lmEoXKZxjo3h/5aUgCxfqDc1KZ7ZfMKFyx9zPzqzbW/cWiDvdFXVHExc4GRinbIxizO5AoGBAIXwJxoSffKSWBf44VmLYOz7oSWpT6rkdwbTV3KtWYqUtkaSm+CqnfDl+kUzEGLkSrnhnng85lT0uem/oaz+ZT3xHR2Pil1mRVltbEAO9vRkZTXbarC2sVcNod0pk4pZWSylyUVWMnrebFJNEIhNgkvTT67icf6M68u1KEzsjt5fAoGAbQDhbfmjgOVUUPDm3noaEtouljfZYOJRm1qDO/nUbYVyTuz5y6mHDBevxMc0z+TyXlSsfvsZUegWH8IySElD1H+3eEzSRkxVrMM07CzqHqnYfJ1RonLmiTOfy7GvPDr/QWPT7A0/eBUudCYHcr/j21JyMjr4dEAr+Z8ZkD1ubt8=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApOp0AOSMksvV0rGgGSUiPcWZVdakHu7gbLz0jxg7WQ+paZT/8QY12y0STs1iA0A2jU1gMfmN8Ts3hdGEtuX8sx0KOQTT9T7ZgzJ6It8BTpxroWkqK9LdjyLPE545+0EYeSVt/k7X6lVVM4ZReZX/3+g4h1TwQCX8MazsNayyezaQ4fn/kJw8VKLovIGWDKPEtQ1VoaRnro5iXC+VSdFn8es+1JuE8+p8xvWlapBeesEBZTwNOxVe2NB7H9sUnXjnAD1si5q2yUrlfVi6FOjnYdEtDlI+fLV8H0l53fAit/jrs+WgKCHP+wi+GHRaVY2aesVopGJPa6givGlkluXUuwIDAQAB
  notifyUrl: http://xid962.natappfree.cc/alipay_notify_url
  returnUrl: https://www.baidu.com
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
#  public static String app_id = "9021000141662885";
#  // 「沙箱环境」商户私钥，你的PKCS8格式RSA2私钥 -【秘钥工具】所创建的公户私钥
#  public static String merchant_private_key = "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCAgNpVn+dQ8h11EPEJHzC+jO9vWxQdfgLP/yr3scbTVCB7gICBcz3lZF+qAvph92MieJbFjvEbcjakWeD1or50XKlbNJpl5C7wIDKf/4VXqxbOTmeTwvmrbakqdBjciVXEZkABzfWbVk3iF2ntwVj+kUZZyAAt9T2Z9MOeSf9IcdtLQZV/lMSLorJ/rPzOKYuB5ekFLLsllv62xL37uoxiB10YJ8mzWNDJMMK1OCyyz1B5iHT6W9UjNvg1rhI8Im/bkc5sSgbEb4cnXkOlrFDzI60Gu3GPTq9TqbHDHe9rBmlLNAJ7S1tv6z85/fG2E3TXSqAMFG6nyr/sqQDyrJCZAgMBAAECggEAFvDqCadGcJkI0UF5Bpve4+XdSRAFg05fyipPzXCbglbeha3nQzUDs9Q7j+qAMMUtmZXVtOdT/AZj4ut40eGABt4UDghSGCaoio30+8NuVrxgkexFaYfBcu1c6gtX9Oc/vJRUkP3n/xdlSBvN+XgvHyNoX9bo0Uua98VOtw+W16PbMOv52RbDHY/x3dUFNC8gJCjMk1lHy9FOKYFq51ZSiQNofo+n/1vRRyU4FZdyvEnlmeMr7/Jfx4PqkaNLPsOoMFgxnpN64D/2Ht+ixZ411Xn0uS2rsfiWpdOVqNO/GmZd8QoLL+IB/bQuzkkm7yAkQQlY+ocxh4DDL7C0qq18kQKBgQC4w86C3e/3HoRVfOmxwE2qTIrweynENpnGgRmhkxD/QIOIRbc+jV7QEUUrZd5fVcAfrFFj7VLhr/Za4c7yWnRvH5DOcg9FBTLopFV+2Tgsv2d3Vmbz66bHRpVEdrjysXLnBzV6ECdCl1YVcDK7+ICCgq1QdeOFkDQWicJuK5pX/wKBgQCyDBAGh7ldkRxGepqd6Re8ukec0EApJZQQJp+5Z9kI0CpDlLvX7Rd7y9INOi5MAz+i2MBCm3gb7mbQ1/zzM1x0sz5PNhHwqhUB9iyHazIpjDlRMH8YNbkMDps4mf7DhsgaCmfQ7nwD2OKbxks6HErXssCgG+uBO5jg3W7WGFTXZwKBgA/6v02KLErPFNrf5sY8v3rPC+UogcA6iKomWDUlJv8scTPD88kxKNYN6FGMieLs46TZnmBqEhT6xu+tP9yt/gvuSvPP4YoynOiJ7er+lmEoXKZxjo3h/5aUgCxfqDc1KZ7ZfMKFyx9zPzqzbW/cWiDvdFXVHExc4GRinbIxizO5AoGBAIXwJxoSffKSWBf44VmLYOz7oSWpT6rkdwbTV3KtWYqUtkaSm+CqnfDl+kUzEGLkSrnhnng85lT0uem/oaz+ZT3xHR2Pil1mRVltbEAO9vRkZTXbarC2sVcNod0pk4pZWSylyUVWMnrebFJNEIhNgkvTT67icf6M68u1KEzsjt5fAoGAbQDhbfmjgOVUUPDm3noaEtouljfZYOJRm1qDO/nUbYVyTuz5y6mHDBevxMc0z+TyXlSsfvsZUegWH8IySElD1H+3eEzSRkxVrMM07CzqHqnYfJ1RonLmiTOfy7GvPDr/QWPT7A0/eBUudCYHcr/j21JyMjr4dEAr+Z8ZkD1ubt8=";
#  // 「沙箱环境」支付宝公钥 -【秘钥填写】后提供给你的支付宝公钥
#  public static String alipay_public_key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApOp0AOSMksvV0rGgGSUiPcWZVdakHu7gbLz0jxg7WQ+paZT/8QY12y0STs1iA0A2jU1gMfmN8Ts3hdGEtuX8sx0KOQTT9T7ZgzJ6It8BTpxroWkqK9LdjyLPE545+0EYeSVt/k7X6lVVM4ZReZX/3+g4h1TwQCX8MazsNayyezaQ4fn/kJw8VKLovIGWDKPEtQ1VoaRnro5iXC+VSdFn8es+1JuE8+p8xvWlapBeesEBZTwNOxVe2NB7H9sUnXjnAD1si5q2yUrlfVi6FOjnYdEtDlI+fLV8H0l53fAit/jrs+WgKCHP+wi+GHRaVY2aesVopGJPa6givGlkluXUuwIDAQAB";
#
#  // 「沙箱环境」服务器异步通知回调地址
#  public static String notify_url = "http://xid962.natappfree.cc/alipay_notify_url";
#  // 「沙箱环境」页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
#  public static String return_url = "https://www.baidu.com";
#  // 「沙箱环境」
#  public static String gatewayUrl = "https://openapi-sandbox.dl.alipaydev.com/gateway.do";