# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 开发
      # 主库数据源
#      master:
#        url: jdbc:mysql://101.42.12.252:3306/psy-test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#        username: root
#        password: 123456qwerQWER=

      master:
        url: jdbc:mysql://127.0.0.1:3306/pocket?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: root
        
      # 本地
#      master:
#        url: jdbc:mysql://localhost:3306/pocket?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#        username: root
#        password: root
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: renxin
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  # 正式
  redis:
    # 地址
    #host: 10.0.24.3
#    host: 127.0.0.1
#    # 端口，默认为6379
#    port: 6379
#    # 数据库索引
#    database: 10
#    # 密码
#    password: 1
    
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 15
    # 密码
    password: dK2FNsDZ4mxmnkN
    
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# token配置
#token:
#  # 令牌自定义标识
#  header: Authorization
#  # 令牌密钥
#  secret: abcdefghijklmnopqrstuvwxyz
#  # 令牌有效期（默认30分钟）
#  expireTime: 120
#
#  # token配置
#app:
#  token:
#    # 令牌自定义标识
#    header: Authorization
#    # 令牌密钥
#    secret: appabcdefghijklmnopqrstuvwxyz
#    # 令牌有效期（默认7天 60*60*24*7）单位s
#    expireTime: 2592000
#  filter:
#    urls: /app/user/bindPhone,app/api/wechatPay/v3/wechatPay,/app/wxPay/**,/app/*/order/**,/app/gauge/result,/app/gauge/result/commit,/app/gauge/questions/list,/app/home/gauge/getInfo,/app/course/detail,/app/course/userSection/saveUserSectionInfo,/app/course/getCourseListByUserId*
