version: '3.3'
services:
  # 数据挂载根目录，替换：/data/ruoyi/
  ruoyi-mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: ruoyi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: RuoYiDev
      MYSQL_DATABASE: ry_vue
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - /data/ruoyi/mysql/log:/var/log/mysql
      - /data/ruoyi/mysql/data:/var/lib/mysql
  ruoyi-redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: ruoyi-redis
    ports:
      - "6379:6379"
    volumes:
      - /data/ruoyi/redis/data:/data
      - /data/ruoyi/redis/log:/var/log/redis
  ruoyi:
    build:
      context: ./ruoyi
      dockerfile: Dockerfile
    container_name: ruoyi-admin
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - /data/ruoyi/admin/data:/app/data
      - /data/ruoyi/admin/upload:/app/upload
      - /data/ruoyi/admin/logs:/app/logs
      - /data/ruoyi/admin/conf:/app/conf
    environment:
      # 可以完全覆盖配置文件 -Dspring.config.location=file:/app/conf/
      - JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/data/heapdump.hprof -Xmx512m -Xms512m -XX:+PrintCommandLineFlags -Dlogback.configurationFile=file:/app/conf/logback.xml
      # 也可以通过环境变量覆盖个别配置
      - RUOYI_PROFILE=/app/upload
      - SPRING_REDIS_HOST=ruoyi-redis
      - spring_datasource_druid_master_url=jdbc:mysql://ruoyi-mysql:3306/ry_vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      - spring_datasource_druid_master_password=RuoYiDev
    extra_hosts:
      - "ruoyi-node:127.0.0.1"
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: ruoyi-dashboard
    ports:
      - "88:80"
    volumes:
      - /data/ruoyi/dashboard/logs:/var/log/nginx
